#!/bin/bash

webpath=""
# webpath="/root/github/allweb"
dirname="`pwd`"
VERSION="1.0.0"
DATE="$(date +%F)"
RELEASE_NAME="allweb-${VERSION}"
BUNDLE_PATH="/root/${RELEASE_NAME}"

# --- warning / success
function fLog(){
  if [ "${1}" -ne 0 ]
  then
    printf "\033[1;31m%b\033[0m" " ${2} \n"
  else
    printf "\033[1;32m%b\033[0m" "${2} \n"
  fi
}

# --- clean build dir
function clean() {
  rm ~/rpmbuild/BUILD/* -rf
  rm ${BUNDLE_PATH} -rf
}

# --- be prepared for rpm build
function configure() {
  mkdir -p "${BUNDLE_PATH}"
  mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}

  # Makefile
  cp ./conf/Makefile "${BUNDLE_PATH}" -f

  # allweb
  fLog 0 ">>> copy  file : [$webpath/node-express-react]"
  npm run gulp-clean
  cp $webpath/node-express-react "./origin" -rf
  # gulp workflow
  npm run gulp-build
  # copy
  cp ./origin/node-express-react "${BUNDLE_PATH}" -rf

  fLog 0 ">>> copy  file : [$webpath/web]"
  cp $webpath/web "${BUNDLE_PATH}" -rf
  # update web-dist files
  cp $webpath/web/dist ${BUNDLE_PATH}/node-express-react/public/ -rf

  # mongodb
  fLog 0 ">>> copy  file : [mongodb-linux-x86_64-rhel70-3.6.4]"
  tar -xf ./resources/mongodb-linux-x86_64-rhel70-3.6.4.tar.gz -C "${BUNDLE_PATH}"
  # node
  fLog 0 ">>> copy  file : [node-v8.11.1-linux-x64]"
  tar -xf ./resources/node-v8.11.1-linux-x64.tar.gz -C "${BUNDLE_PATH}"

  # tar
  fLog 0 ">>> build file : [${RELEASE_NAME}.tar.gz]"
  tar -czf ~/rpmbuild/SOURCES/"${RELEASE_NAME}.tar.gz" -C /root "${RELEASE_NAME}"
}

# --- build rpm
function build() {
  fLog 0 ">>> run rpmbuild ... "
  rpmbuild -ba allweb.spec
}

# --- help info
# # 显示帮助信息
showUsage() {
  echo
  echo "description: build rpm package for allweb."
  echo "command: bash build [--param] "
  echo " |"
  echo " |______ param: [--help | -h] => show usage info."
  echo " |______ param: [--webpath  ] [path/to/allweb] => build rpm package for allweb."
  echo " |"
  echo " |______ example: bash build --help"
  echo " |______ example: bash build -h"
  echo " |______ example: bash build --webpath /root/github/allweb"
  echo
}

# --- MAIN ---
Main() {
  while [ -n "$1" ]; do
    case "$1" in
      --help | -h )
      showUsage
      exit 0
      ;;
      --webpath | --path )
      webpath="$2"
      shift
      ;;
    esac
    shift
  done

  if [ -z "$webpath" ]; then
    fLog 1 "the param [webpath] is necessary, it's a path of allweb code directory."
    exit 1
  fi

  # -
  clean
  # -
  configure
  # -
  build
}

Main "$1" "$2"
