#!/bin/bash

location=`pwd`
whoami=`whoami`

fileName="$1"
fileType="${fileName##*.}"
imageType=('jpg' 'png' 'jpeg')

inArray() {
  local array="$1"
  local key="$2"
  local booln=`echo ${array[@]} | grep -wq "$key" && echo 1 || echo 0`
  return $booln
}

# extentions: ${file##*.}”
# filename: ${file%.*}
inArray $imageType $fileType
if [ "$?" == "0" ]; then
  notify-send "set-as-wallpaper: need a image file!"
  exit 1
fi

# Set As Wallpaper
gsettings set org.gnome.desktop.background picture-uri file:///$location/$1

sleep 1

# Make your wallpaper blurry
mkdir /home/$whoami/Pictures -p
convert -blur 5x5 ~/.cache/wallpaper/* ~/Pictures/gdmlock.jpg

sleep 1

# Copy wallpaper in system directory for gdm3 lockscreen
pkexec cp -f /home/$whoami/Pictures/gdmlock.jpg /usr/share/backgrounds/

# Enjoy!
