#!/bin/bash
dirname=`pwd`
mongodb="$dirname/../../mongodb-linux-x86_64-rhel70-3.6.4"
node="$dirname/../../node-v8.11.1-linux-x64"
yapi="$dirname/../../my-yapi"
dbpath="$dirname/../data"
dblogpath="$dirname/../logs"

# # 删除旧数据
rm "$node" -rf
rm "$mongodb" -rf
rm "$yapi" -rf

# # 安装基础环境
yum -y install unzip

# # node -----------------------

echo '>>> now install nodejs.package ... '
tar -xf "$node.gzip" -C "$dirname/../../"
for biname in `ls $node/bin`
do
  sudo ln -s "$node/bin/$biname" /usr/bin -f
done

# # 设置npm镜像源为国内镜像
npm config set registry https://registry.npm.taobao.org

# # mongodb ---------------------

# # 解压mongodb二进制包并加入系统变量
echo '>>> now install mongodb.package ... '
tar -xf "$mongodb.tgz" -C "$dirname/../../"
for biname in `ls $mongodb/bin`
do
  sudo ln -s "$mongodb/bin/$biname" /usr/bin -f
done

# # 路径存入文件
touch /etc/frontend
sed '/MongodbPath=/'d /etc/frontend -i
echo "MongodbPath=$dirname/.." >> /etc/frontend

# # 清理旧数据
# rm "$dbpath" -rf
# rm "$dblogpath" -rf

echo '>>> now registry mongodb.service ... '
# # 获取项目路径
cp "$dirname/mongodb" /etc/init.d -f
sudo chmod a+x /etc/init.d/mongodb
chkconfig --add /etc/init.d/mongodb
chkconfig mongodb on

echo '>>> now start mongodb.service ... '
bash "mongodb" --start
echo ">>> now set mongodb-backup crontab service ... "
bash "mongodb" --crontab -t "10.0.6.200"

# # yapi ---------------------------
echo '>>> now install yapi.package'
unzip -q "${yapi}.zip" -d "$dirname/../../"
bash "yapi" start

cp "$dirname/yapi" /etc/init.d -f
sudo chmod a+x /etc/init.d/yapi
chkconfig --add /etc/init.d/yapi
chkconfig yapi on

echo ">>> init done."
