#!/bin/bash
dirname=`pwd`
mongodb_pack="$dirname/resource/mongodb-4.0.10.tar.gz"
node_pack="$dirname/resource/node-v12.14.0-linux-x64.tar.gz"
yapi_pack="$dirname/resource/yapi.tar.gz"

env_install() {
  frontendScriptPath=`pwd`
  # # 安装基础环境
  yum -y install unzip

  # # define script path
  sed '/frontendScriptPath=/d' ./conf/frontend.sh -i
  sed '/frontendScriptPath=/d' ./conf/frontend.conf -i
  echo "export frontendScriptPath=$frontendScriptPath" >> ./conf/frontend.sh
  echo "frontendScriptPath=$frontendScriptPath" >> ./conf/frontend.conf

  # # 配置环境文件
  cp ./conf/frontend.conf /etc
  cp ./conf/mongod.conf /etc
  cp ./conf/frontend.sh /etc/profile.d/
}

# # env prepare
get_env_path() {
  path=$1
  for var in `cat $1`; do
    a=`echo $var | awk -F '=' '{print $1}'`
    b=`echo $var | awk -F '=' '{print $2}'`
    export $a=$b
  done
}

# # node -----------------------

nodejs_install() {
  echo '>>> now install nodejs.package ... '
  tar -xf $mongodb_pack -C $FrontendServicePath
  for biname in `ls $nodePath/bin`
  do
    sudo ln -s "$nodePath/bin" /usr/bin -f
  done

  # # 设置npm镜像源为国内镜像
  npm config set registry https://registry.npm.taobao.org
}

# # mongodb ---------------------

# # 解压mongodb二进制包并加入系统变量
mongodb_install() {
  echo '>>> now install mongodb.package ... '
  tar -xf "$mongodb_pack" -C $FrontendServicePath
  for biname in `ls $mongodbPath/bin`
  do
    sudo ln -s "$mongodbPath/bin/$biname" /usr/bin -f
  done
}

# # yapi ------------------------

# # 解压yapi并加入环境变量
yapi_install() {
  echo '>>> now install yapi.package ... '
  tar -xf "$yapi_pack" -C $FrontendServicePath
}


service_registry() {
  echo '>>> now registry mongodb.service ... '
  cp ./conf/mongodb.service /usr/lib/systemd/system/ -f
  systemctl daemon-reload
  systemctl enable mongodb
  systemctl start mongodb
  echo '>>> now registry yapi.service ... '
  cp ./conf/yapi.service /usr/lib/systemd/system/ -f
  systemctl daemon-reload
  systemctl enable yapi
  systemctl start yapi
  # echo ">>> now registry mongodb-backup crontab service ... "
  # bash "mongodb" --crontab -t "10.0.6.200"
}

Main() {
  env_install
  get_env_path './conf/frontend.conf'
  nodejs_install
  mongodb_install
  yapi_install
  service_registry
}

Main $@

echo ">>> node/mongodb/yapi init done."
