#!/bin/bash
dirname=`pwd`
mongodb_pack=$dirname/resource/mongodb-4.0.10.tar.gz
node_pack=$dirname/resource/node-v12.14.0-linux-x64.tar.gz
yapi_pack=$dirname/resource/yapi.tar.gz

# # warning / success print
function fLog(){
  if [ "${1}" -ne 0 ]
  then
    echo
    printf "\033[1;31m%b\033[0m" " ${2} \n"
    echo
  else
    echo
    printf "\033[1;32m%b\033[0m" "${2} \n"
    echo
  fi
}

env_prepare() {
  fLog 0 '>>> evn prepare ... '
  frontendScriptPath=`pwd`
  # # 安装基础环境
  yum -y install net-tools

  # # define script path
  sed '/frontendScriptPath=/d' ./conf/frontend.sh -i
  sed '/frontendScriptPath=/d' ./conf/frontend.conf -i
  echo "export frontendScriptPath=$frontendScriptPath" >> ./conf/frontend.sh
  echo "frontendScriptPath=$frontendScriptPath" >> ./conf/frontend.conf
  pm2 delete all

  # # 配置环境文件
  cp ./conf/frontend.conf /etc -f
  cp ./conf/mongod.conf /etc -f
  cp ./conf/frontend.sh /etc/profile.d/ -f
  sudo chmod a+x ./yapi-cmd
  cp ./yapi-cmd /etc/ -f
}

# # env prepare
get_env_path() {
  path=$1
  for var in `cat $1`; do
    a=`echo $var | awk -F '=' '{print $1}'`
    b=`echo $var | awk -F '=' '{print $2}'`
    export $a=$b
  done
}

# # clean
clean() {
  fLog 0 '>>> clear cache ... '
  systemctl stop yapi
  systemctl stop mongodb
  systemctl disable yapi
  systemctl disable mongodb
  rm $frontendServicePath/mongodb -rf
  rm $frontendServicePath/yapi -rf
  rm $frontendServicePath/node-linux-x64 -rf
}

# # node -----------------------

nodejs_install() {
  fLog 0 '>>> now install nodejs.package ... '
  tar -xf $node_pack -C $frontendServicePath
  sudo ln -s $nodePath/bin/* /usr/bin -f

  # # 设置npm镜像源为国内镜像
  npm config set registry https://registry.npm.taobao.org
}

# # mongodb ---------------------

# # 解压mongodb二进制包并加入系统变量
mongodb_install() {
  fLog 0 '>>> now install mongodb.package ... '
  tar -xf $mongodb_pack -C $frontendServicePath
  sudo ln -s $mongoPath/bin/* /usr/bin -f
}

# # yapi ------------------------

# # 解压yapi并加入环境变量
yapi_install() {
  fLog 0 '>>> now install yapi.package ... '
  tar -xf $yapi_pack -C $frontendServicePath
  if [ ! -d $frontendServicePath/yapi/vendors/node_modules ]; then
    tar -xf $frontendServicePath/yapi/vendors/node_modules.tar.gz -C $frontendServicePath/yapi/vendors/
  fi
}


service_registry() {
  # echo ">>> now registry pm2-root.service ... "
  # pm2 startup
  cp ./conf/mongodb.service /usr/lib/systemd/system/ -f
  cp ./conf/yapi.service /usr/lib/systemd/system/ -f
  systemctl daemon-reload
  systemctl enable mongodb
  systemctl enable yapi
  fLog 0 '>>> now registry mongodb.service ... '
  systemctl start mongodb
  sleep 2
  fLog 0 '>>> now registry yapi.service ... '
  systemctl start yapi
  # echo ">>> now registry mongodb-backup crontab service ... "
  # bash "mongodb" --crontab -t "10.0.6.206"
}

finally() {
  systemctl stop mongodb
  systemctl start mongodb
}

Main() {
  env_prepare
  get_env_path './conf/frontend.conf'
  clean
  nodejs_install
  mongodb_install
  yapi_install
  service_registry
  fLog 0 ">>> node|mongodb|yapi init done."
}

Main $@