#!/bin/bash

location=`pwd`
whoami=`whoami`

# check file
if [ -d $location/$1 ]; then
 notify-send "Warning" "You select a directory, Cancelled." -u normal
 exit
fi

mkdir ~/Pictures/ -p

# Set As Wallpaper
gsettings set org.gnome.desktop.background picture-uri file:///$location/$1

sleep 1

# Make your wallpaper blurry
mkdir /home/$whoami/Pictures -p
convert -blur 20x20 $location/$1 ~/Pictures/gdmlock.jpg

sleep 1

# Copy wallpaper in system directory for gdm3 lockscreen
pkexec cp -f /home/$whoami/Pictures/gdmlock.jpg /usr/share/backgrounds/

# Enjoy!
